menu:
  home:
    label: Home
    relativePath: /
  blog:
    label: Blog
    relativePath: /blog/
  projects:
    label: Projects
    relativePath: /projects/
  talks:
    label: Talks
    relativePath: /talks/
  about_me:
    label: About Me
    relativePath: /about-me/

social:
  github:
    url: https://github.com/StefanoOrdine

fullResumeRelativePath: /assets/pdf/CV-Europass-20170320-Ordine-Stefano-IT.pdf
